import localFont from "next/font/local";
import "./globals.css";

const projectFont = localFont({
  src: "./(fonts)/RussoOne-Regular.woff",
  variable: "--font-regular",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={projectFont.variable}>{children}</body>
    </html>
  );
}
